/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SshAccessValidationDto {
    /**
     * Whether the SSH access token is valid
     */
    'valid': boolean;
    /**
     * ID of the box this SSH access is for
     */
    'boxId': string;
    /**
     * Guest unix user the SSH session runs as
     */
    'unixUser'?: string;
    /**
     * Non-sensitive identifier of the SSH access token, for audit correlation
     */
    'tokenId'?: string;
}

