/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the CreateSshAccessBodyDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSshAccessBodyDto{}

// CreateSshAccessBodyDto struct for CreateSshAccessBodyDto
type CreateSshAccessBodyDto struct {
	// Unix user for SSH access (camelCase form)
	UnixUser *string `json:"unixUser,omitempty" validate:"regexp=^([a-z_][a-z0-9_-]{0,31})?$"`
	AdditionalProperties map[string]interface{}
}

type _CreateSshAccessBodyDto CreateSshAccessBodyDto

// NewCreateSshAccessBodyDto instantiates a new CreateSshAccessBodyDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSshAccessBodyDto() *CreateSshAccessBodyDto {
	this := CreateSshAccessBodyDto{}
	return &this
}

// NewCreateSshAccessBodyDtoWithDefaults instantiates a new CreateSshAccessBodyDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSshAccessBodyDtoWithDefaults() *CreateSshAccessBodyDto {
	this := CreateSshAccessBodyDto{}
	return &this
}

// GetUnixUser returns the UnixUser field value if set, zero value otherwise.
func (o *CreateSshAccessBodyDto) GetUnixUser() string {
	if o == nil || IsNil(o.UnixUser) {
		var ret string
		return ret
	}
	return *o.UnixUser
}

// GetUnixUserOk returns a tuple with the UnixUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSshAccessBodyDto) GetUnixUserOk() (*string, bool) {
	if o == nil || IsNil(o.UnixUser) {
		return nil, false
	}
	return o.UnixUser, true
}

// HasUnixUser returns a boolean if a field has been set.
func (o *CreateSshAccessBodyDto) HasUnixUser() bool {
	if o != nil && !IsNil(o.UnixUser) {
		return true
	}

	return false
}

// SetUnixUser gets a reference to the given string and assigns it to the UnixUser field.
func (o *CreateSshAccessBodyDto) SetUnixUser(v string) {
	o.UnixUser = &v
}

func (o CreateSshAccessBodyDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSshAccessBodyDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UnixUser) {
		toSerialize["unixUser"] = o.UnixUser
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSshAccessBodyDto) UnmarshalJSON(data []byte) (err error) {
	varCreateSshAccessBodyDto := _CreateSshAccessBodyDto{}

	err = json.Unmarshal(data, &varCreateSshAccessBodyDto)

	if err != nil {
		return err
	}

	*o = CreateSshAccessBodyDto(varCreateSshAccessBodyDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "unixUser")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSshAccessBodyDto struct {
	value *CreateSshAccessBodyDto
	isSet bool
}

func (v NullableCreateSshAccessBodyDto) Get() *CreateSshAccessBodyDto {
	return v.value
}

func (v *NullableCreateSshAccessBodyDto) Set(val *CreateSshAccessBodyDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSshAccessBodyDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSshAccessBodyDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSshAccessBodyDto(val *CreateSshAccessBodyDto) *NullableCreateSshAccessBodyDto {
	return &NullableCreateSshAccessBodyDto{value: val, isSet: true}
}

func (v NullableCreateSshAccessBodyDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSshAccessBodyDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


